// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics_snapshots.sql

package sqlc

import (
	"context"
	"time"
)

const deleteMetricsOlderThan = `-- name: DeleteMetricsOlderThan :exec
DELETE FROM metrics_snapshots WHERE created_at < ?
`

func (q *Queries) DeleteMetricsOlderThan(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteMetricsOlderThan, createdAt)
	return err
}

const getMetricsSince = `-- name: GetMetricsSince :many
SELECT id, cpu_percent, mem_used_percent, mem_used_bytes, total_visits, unique_visitors, created_at
FROM metrics_snapshots
WHERE created_at >= ?
ORDER BY created_at ASC
`

func (q *Queries) GetMetricsSince(ctx context.Context, createdAt time.Time) ([]MetricsSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, getMetricsSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricsSnapshot{}
	for rows.Next() {
		var i MetricsSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.CPUPercent,
			&i.MemUsedPercent,
			&i.MemUsedBytes,
			&i.TotalVisits,
			&i.UniqueVisitors,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMetricsSnapshot = `-- name: InsertMetricsSnapshot :exec
INSERT INTO metrics_snapshots (cpu_percent, mem_used_percent, mem_used_bytes, total_visits, unique_visitors)
VALUES (?, ?, ?, ?, ?)
`

type InsertMetricsSnapshotParams struct {
	CPUPercent     float64
	MemUsedPercent float64
	MemUsedBytes   int64
	TotalVisits    int64
	UniqueVisitors int64
}

func (q *Queries) InsertMetricsSnapshot(ctx context.Context, arg InsertMetricsSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, insertMetricsSnapshot,
		arg.CPUPercent,
		arg.MemUsedPercent,
		arg.MemUsedBytes,
		arg.TotalVisits,
		arg.UniqueVisitors,
	)
	return err
}
