// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type MetricsSnapshot struct {
	ID             int64
	CPUPercent     float64
	MemUsedPercent float64
	MemUsedBytes   int64
	TotalVisits    int64
	UniqueVisitors int64
	CreatedAt      time.Time
}

type PageView struct {
	ID          int64
	Path        string
	VisitorHash string
	CreatedAt   time.Time
}
