// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: page_views.sql

package sqlc

import (
	"context"
	"time"
)

const countTotalPageViews = `-- name: CountTotalPageViews :one
SELECT COUNT(*) FROM page_views
`

func (q *Queries) CountTotalPageViews(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTotalPageViews)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUniqueVisitors = `-- name: CountUniqueVisitors :one
SELECT COUNT(DISTINCT visitor_hash) FROM page_views WHERE visitor_hash != ''
`

func (q *Queries) CountUniqueVisitors(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUniqueVisitors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePageViewsOlderThan = `-- name: DeletePageViewsOlderThan :exec
DELETE FROM page_views WHERE created_at < ?
`

func (q *Queries) DeletePageViewsOlderThan(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deletePageViewsOlderThan, createdAt)
	return err
}

const insertPageView = `-- name: InsertPageView :exec
INSERT INTO page_views (path, visitor_hash) VALUES (?, ?)
`

type InsertPageViewParams struct {
	Path        string
	VisitorHash string
}

func (q *Queries) InsertPageView(ctx context.Context, arg InsertPageViewParams) error {
	_, err := q.db.ExecContext(ctx, insertPageView, arg.Path, arg.VisitorHash)
	return err
}
