// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"time"
)

type Querier interface {
	CountTotalPageViews(ctx context.Context) (int64, error)
	CountUniqueVisitors(ctx context.Context) (int64, error)
	DeleteMetricsOlderThan(ctx context.Context, createdAt time.Time) error
	DeletePageViewsOlderThan(ctx context.Context, createdAt time.Time) error
	GetMetricsSince(ctx context.Context, createdAt time.Time) ([]MetricsSnapshot, error)
	InsertMetricsSnapshot(ctx context.Context, arg InsertMetricsSnapshotParams) error
	InsertPageView(ctx context.Context, arg InsertPageViewParams) error
}

var _ Querier = (*Queries)(nil)
